add panel size prop
KlutchCard/klutch-js pull request #110
Opened 2022-06-30 20:18 UTC by victorabarros

depends on:
- [ ] https://github.com/KlutchCard/graphql/pull/178

2022-07-01 01:12 UTC, renatost requested changes

2022-07-01 01:12 UTC, renatost commented on src/entities/Recipe.ts
> +  size?: RecipePanelSize
I dont think that should be optional

2022-07-01 01:37 UTC, victorabarros commented on src/entities/Recipe.ts
> +  size?: RecipePanelSize
Assuming that's nullable, I don't think optional is a problem.
But if you don't think it should be nullable, we can talk.

2022-07-05 17:42 UTC, renatost approved these changes

2022-07-05 17:42 UTC, merged